#Setting the parent directory(working directory) to the project name  
dirname(getwd())
setwd("C:/Users/jtuch/Desktop/fama miller exam/Fama Miller Center RA Test")
getwd()

#I made the following subdirectories under the Fama Miller Center RA Test Directory- Code, Data, Output 
 
#Pulling stock price data from Yahoo Finance historical data- scraping data by co_cusip and the date range January 1, 1970 to January 1, 2017.  
install.packages("quantmod")
library(quantmod)
getSymbols("ABT", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("HON", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("AEP", from = "1970-01-01", to = "2017-01-01",aQuto.assign = TRUE)
getSymbols("BA", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("BMY", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("CPB", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("CAT", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("CVX", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("KO", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("CL", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("ED", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("GLW", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("DE", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("D", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("DWDP", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("ETN", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("XOM", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("F", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("GD", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("GE", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("GT", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("HAL", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("HSY", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("IBM", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("IP", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("K", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("KMB", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("KR", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("SPGI", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("CVS", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("MRK", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("ETR", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("MMM", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("MSI", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("NSC", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("XEL", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("FE", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PPG", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PCG", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("SRE", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PEP", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PFE", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("EXC", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("MO", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("COP", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PG", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("PEG", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("RTN", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)
getSymbols("ROK", from = "1970-01-01", to = "2017-01-01",auto.assign = TRUE)

#Merged these datasets of stock prices into a final dataset "merge", merged the data on the date.  
merge <- merge(ABT, AEP, BA, BMY, CAT, CL, COP, CPB, CVS, CVX, D, DE, DWDP, ED, ETN, ETR, EXC, F, FE, GD, GE, FE, GLW, GT, HAL, HON, HSY, IBM, IP, K, KMB, KO, KR, MMM, MO, MRK, MSI, NSC, PCG, PEG, PEP, PFE, PG, ROK, RTN, SPGI, SRE, XEL, XOM, by = c("column 0"));
View(merge)


# Calculating the equal-weight return on the days listed in the file "dates.csv"
#From my understanding of the SAS convention of date time- the number 0 corresponds to the first 
#day on the interval of time examined- or 01-01-1970, the number 1 corresponds to 01-02-1970 and so on- I physically converted the SAS date times to standard format- which is highlighted in red in the Excel spreadsheet- merge- in the Output folder.  This column is called Final Date Converted from SAS datetime.
#The equal weight return is calculated for all the dates in the merge file for simplicity purposes.  This is found in column LB of the merge spreadsheet- the column is titled equal weight return.   
library(xlsx)
write.xlsx(merge, "C:\Users\jtuch\merge.xlsx")
write.csv(merge, "merge.csv")
dates <- read.csv("C:/Users/jtuch/Desktop/fama miller exam/Fama Miller Center RA Test/Data/Output/dates.csv", sep="")
View(dates)
dates <- cbind(dates, dates/366) 
getwd() 

# Calculating the equal-weight return- this is found in the last column of merge1- a dataset which is the subset of merge, merg1 is saved in the output file. 
#The process of aggregating of daily stock returns into a monthly stock file is done on the merge1 tab of the merge file, these results are then saved in the file January aggregated prices- which is saved under the 
#folder Output. 


#Aggregated_Data_merged_with_Risk_Free_Interest_Rates contains the dataset that will be using to run the regression in part c, this merged dataset is imported below. 
library(readxl)
F_F_Research_Data_Factors <- read_excel("fama miller exam/Fama Miller Center RA Test/Data/F-F_Research_Data_Factors.xls")
View(F_F_Research_Data_Factors)
Aggregated_Data_merged_with_Risk_Free_Interest_Rates <- read_excel("C:/Users/jtuch/Downloads/fama-miller-exam/Aggregated Data-merged with Risk Free Interest Rates.xlsx")
View(Aggregated_Data_merged_with_Risk_Free_Interest_Rates)

#Finding the market beta(B) of each stock, the lag in each regression accounts for the risk-free rate for the previous five years, took a subsample of tickers, for simplicity purposes  
lm(formula = ABT.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = AEP.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = ABT.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = BA.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = BMY.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = CAT.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = CL.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = COP.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = CPB.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = CVS.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = CVX.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = D.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = DE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = DWDP.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = ED.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = ETN.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = ETR.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = EXC.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = F.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = FE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = GD.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = GE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = FE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = GLW.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = GT.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = HAL.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = HON.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = HSY.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = IBM.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = K.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = KMB.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = KR.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = MMM.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = MO.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = MRK.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = MSI.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = NSC.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = PCG.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = PEG.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = PEP.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = PFE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = PG.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = ROK.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = RTN.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = SPGI.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = SRE.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = XEL.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)
lm(formula = XOM.Open ~ lag(MktRF, -1) + lag(MktRF,-2) + lag(MktRF,-3) +  lag(MktRF,-4) + lag(MktRF,-5), Aggregated_Data_merged_with_Risk_Free_Interest_Rates)

#..etc. for the rest of the stock prices, you would just change the ticker symbol in the formula 
# From the output of these regressions in the console, I constructed an Excel file (portfolio-returns), in which 3c., d., and e. are calculated- this excel file was then saved as a csv file 
